server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-servicio
          uri: lb://usuario-servicio
          predicates:
            - Path=/usuario/**
        - id: carro-servicio
          uri: lb://carro-servicio
          predicates:
            - Path=/carro/**
        - id: moto-servicio
          uri: lb://moto-servicio
          predicates:
            - Path=/moto/**